<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Receipt {{ $payment->receipt_number }}</title>
    <style>
        /* Kanduhulhudhoo Council letterhead palette (design/council-ds). */
        * { box-sizing: border-box; margin: 0; padding: 0; }
        body { font-family: 'Noto Sans Thaana', ui-sans-serif, system-ui, -apple-system, "Segoe UI", Roboto, sans-serif; color: #12203A; font-size: 13px; padding: 40px; }
        h1 { font-size: 22px; margin-bottom: 2px; letter-spacing: -0.02em; }
        .muted { color: #6B7888; }
        .letterhead { display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 14px; border-bottom: 2px solid #1D2B45; padding-bottom: 16px; }
        .letterhead img { height: 52px; }
        .contact { text-align: right; font-size: 11px; color: #6B7888; line-height: 1.55; }
        .contact strong { color: #12203A; }
        .header { display: flex; justify-content: space-between; align-items: flex-end; margin-bottom: 28px; }
        .header .right { text-align: right; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
        th { text-align: left; font-size: 11px; text-transform: uppercase; letter-spacing: .08em; color: #9AA6B4; border-bottom: 1px solid #DBE1E8; padding: 6px 8px; font-weight: 700; }
        td { padding: 8px; border-bottom: 1px solid #E6EAEF; }
        .num { text-align: right; font-variant-numeric: tabular-nums; white-space: nowrap; }
        .total-row td { border-top: 2px solid #1D2B45; border-bottom: none; font-weight: 700; font-size: 15px; }
        .footer { margin-top: 32px; padding-top: 12px; border-top: 1px solid #DBE1E8; font-size: 12px; color: #6B7888; }
    </style>
    @include('pdf.partials.fonts')
</head>
<body>
    <div class="letterhead">
        <img src="data:image/png;base64,{{ base64_encode(file_get_contents(public_path('images/council/lockup-horizontal-color.png'))) }}" alt="Secretariat of the Kanduhulhudhoo Council">
        <div class="contact">
            <p><strong>Secretariat of the Kanduhulhudhoo Council</strong></p>
            <p>Ga. Kanduhulhudhoo, Republic of Maldives</p>
            <p>Tel 6820020 · info@kanduhulhudhoo.gov.mv</p>
        </div>
    </div>

    <div class="header">
        <div>
            <p class="muted" style="font-size:11px;text-transform:uppercase;letter-spacing:.08em">Official payment receipt</p>
        </div>
        <div class="right">
            <h1>Receipt {{ $payment->receipt_number }}</h1>
            <p class="muted">Payment date: <strong>{{ $payment->payment_date->format('j F Y') }}</strong></p>
            <p class="muted">Method: {{ $payment->method->label() }}@if ($payment->reference) · Ref: {{ $payment->reference }}@endif</p>
        </div>
    </div>

    <p style="margin-bottom:16px">
        Received from <strong>{{ $payment->invoice->lease->tenant->name }}</strong>
        @if ($payment->invoice->lease->tenant->registryNumber())
            ({{ $payment->invoice->lease->tenant->registryNumber() }})
        @endif
        against invoice <strong>{{ $payment->invoice->number }}</strong>
        — {{ $payment->invoice->lease->property->name }},
        {{ $payment->invoice->period_start->format('F Y') }}.
    </p>

    <table>
        <thead>
            <tr>
                <th>Allocation</th>
                <th class="num">Amount</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>Rent &amp; charges</td>
                <td class="num">{{ $payment->principalAllocated()->format() }}</td>
            </tr>
            <tr>
                <td>Late fine</td>
                <td class="num">{{ $payment->fineAllocated()->format() }}</td>
            </tr>
            <tr class="total-row">
                <td>Total received</td>
                <td class="num">{{ $payment->amount()->format() }}</td>
            </tr>
        </tbody>
    </table>

    <div class="footer">
        <p><strong>Balance remaining on invoice {{ $payment->invoice->number }}:</strong> {{ $payment->invoice->outstandingTotal()->format() }}</p>
        <p>This receipt was generated by {{ config('app.name') }}. Receipt numbers are sequential and never reissued.</p>
    </div>
</body>
</html>
