<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Receipt {{ $payment->receipt_number }}</title>
    <style>
        * { box-sizing: border-box; margin: 0; padding: 0; }
        body { font-family: ui-sans-serif, system-ui, -apple-system, "Segoe UI", Roboto, sans-serif; color: #172B4D; font-size: 13px; padding: 40px; }
        h1 { font-size: 22px; margin-bottom: 2px; }
        .muted { color: #626F86; }
        .header { display: flex; justify-content: space-between; margin-bottom: 28px; border-bottom: 2px solid #172B4D; padding-bottom: 16px; }
        .header .right { text-align: right; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
        th { text-align: left; font-size: 11px; text-transform: uppercase; letter-spacing: .05em; color: #626F86; border-bottom: 1px solid #DFE1E6; padding: 6px 8px; }
        td { padding: 8px; border-bottom: 1px solid #EBECF0; }
        .num { text-align: right; font-variant-numeric: tabular-nums; white-space: nowrap; }
        .total-row td { border-top: 2px solid #172B4D; border-bottom: none; font-weight: 700; font-size: 15px; }
        .footer { margin-top: 32px; padding-top: 12px; border-top: 1px solid #DFE1E6; font-size: 12px; color: #626F86; }
    </style>
</head>
<body>
    <div class="header">
        <div>
            <h1>{{ config('app.name') }}</h1>
            <p class="muted">Official payment receipt</p>
        </div>
        <div class="right">
            <h1>Receipt {{ $payment->receipt_number }}</h1>
            <p class="muted">Payment date: <strong>{{ $payment->payment_date->format('j F Y') }}</strong></p>
            <p class="muted">Method: {{ $payment->method->label() }}@if ($payment->reference) · Ref: {{ $payment->reference }}@endif</p>
        </div>
    </div>

    <p style="margin-bottom:16px">
        Received from <strong>{{ $payment->invoice->lease->tenant->name }}</strong>
        @if ($payment->invoice->lease->tenant->registryNumber())
            ({{ $payment->invoice->lease->tenant->registryNumber() }})
        @endif
        against invoice <strong>{{ $payment->invoice->number }}</strong>
        — {{ $payment->invoice->lease->property->name }},
        {{ $payment->invoice->period_start->format('F Y') }}.
    </p>

    <table>
        <thead>
            <tr>
                <th>Allocation</th>
                <th class="num">Amount</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>Rent &amp; charges</td>
                <td class="num">{{ $payment->principalAllocated()->format() }}</td>
            </tr>
            <tr>
                <td>Late fine</td>
                <td class="num">{{ $payment->fineAllocated()->format() }}</td>
            </tr>
            <tr class="total-row">
                <td>Total received</td>
                <td class="num">{{ $payment->amount()->format() }}</td>
            </tr>
        </tbody>
    </table>

    <div class="footer">
        <p><strong>Balance remaining on invoice {{ $payment->invoice->number }}:</strong> {{ $payment->invoice->outstandingTotal()->format() }}</p>
        <p>This receipt was generated by {{ config('app.name') }}. Receipt numbers are sequential and never reissued.</p>
    </div>
</body>
</html>
